### ISSUE TITLE
TODO:  Give suggested my.cnf about MySQL 8.0

### ISSUE THREAD

**Issue by andyli029** [andyli029/mysql-server-mysql-8.0.30#120]
StoneDB 5.7
```

```

StoneDB 8.0
```

```

**Comment by lujiashun** [comment]
1. sql mode delete "NO_AUTO_CREATE_USER" option

**Comment by lujiashun** [comment]
Ignoring --secure-file-priv value as server is running with --initialize(-insecure).
ER_SEC_FILE_PRIV_EMPTY eng "Insecure configuration for --secure-file-priv: Current value does not restrict location of generated files. Consider setting it to a valid, non-empty path."
