### ISSUE TITLE
[Notes]: select INTO OUTFILE

### ISSUE THREAD

**Issue by andyli029** [andyli029/mysql-server-mysql-8.0.30#36]
`stonedb 5.7`
`innodb`
```
mysql> select * from ii INTO OUTFILE "li_into_ii";
Query OK, 3 rows affected (0.01 sec)
```
`tianmu`
```
mysql> select * from tt INTO DUMPFILE "li_into_tt_dump";
ERROR 6 (HY000): The query includes syntax that is not supported by the storage engine. Either restructure the query with supported syntax, or enable the MySQL core::Query Path in config file to execute the query with reduced performance.
```

**Comment by andyli029** [comment]
<img width="650" alt="image" src="https://user-images.githubusercontent.com/15212006/186586188-d9d325cb-763d-4dab-99e7-579c7e7afae0.png">

**Comment by lujiashun** [comment]
0. secure_file_priv=''  in my.cnf
1.
1.1.1
CREATE TABLE `tmp_tianmu` (
`id` int(11) NOT NULL,
`name` varchar(10) DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=tianmu;

1.1.2
CREATE TABLE `tmp_tianmu1` (
`id` int(11) NOT NULL,
`name` varchar(10) DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=tianmu;
1.2.1
CREATE TABLE `tmp_innodb` (
`id` int(11) NOT NULL,
`name` varchar(10) DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=innodb;

1.2.2
CREATE TABLE `tmp_innodb1` (
`id` int(11) NOT NULL,
`name` varchar(10) DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=innodb;
2. 
2.1.1
insert into tmp_tianmu value(1,'lujs');
insert into tmp_tianmu value(2,'lujs');
insert into tmp_tianmu value(3,'lujs');
insert into tmp_tianmu value(4,'lujs');
2.1.2
insert into tmp_tianmu1 value(1,'lujs');
2.2.1 
insert into tmp_innodb value(1,'lujs');
insert into tmp_innodb value(2,'lujs');
insert into tmp_innodb value(3,'lujs');
insert into tmp_innodb value(4,'lujs');

2.2.2
insert into tmp_innodb1 value(1,'lujs');
3.
3.1 
select * from tmp_tianmu INTO OUTFILE "tmp_tianmu.csv";
select * from tmp_tianmu1 INTO DUMPFILE "tmp_tianmu.csv3";
3.2
select * from tmp_innodb INTO OUTFILE "tmp_innodb.csv";
select * from tmp_innodb1 INTO DUMPFILE "tmp_innodb.csv2";

**Comment by lujiashun** [comment]
```
mysql> use lujs;
Database changed

mysql> CREATE TABLE `tmp_tianmu1` (
    -> `id` int(11) NOT NULL,
    -> `name` varchar(10) DEFAULT NULL,
    -> PRIMARY KEY (`id`)
    -> ) ENGINE=tianmu;
Query OK, 0 rows affected, 1 warning (0.02 sec)

mysql> CREATE TABLE `tmp_innodb1` (
    -> `id` int(11) NOT NULL,
    -> `name` varchar(10) DEFAULT NULL,
    -> PRIMARY KEY (`id`)
    -> ) ENGINE=innodb;
Query OK, 0 rows affected, 1 warning (0.07 sec)

mysql> insert into tmp_tianmu1 value(1,'lujs');
Query OK, 1 row affected (0.01 sec)

mysql> insert into tmp_innodb1 value(1,'lujs');
Query OK, 1 row affected (0.00 sec)

mysql> select * from tmp_innodb1 INTO DUMPFILE "tmp_innodb.csv2";
ERROR 1086 (HY000): File 'tmp_innodb.csv2' already exists
mysql> select * from tmp_innodb1 INTO DUMPFILE "tmp_innodb.csv3";
Query OK, 1 row affected (0.00 sec)

mysql> select * from tmp_tianmu1 INTO DUMPFILE "tmp_tianmu.csv3";
Query OK, 1 row affected (0.00 sec)
```
