### ISSUE TITLE
TODO：fix  List<Item> to mem_root_deque<Item *>  by MySQL 8.0

### ISSUE THREAD

**Issue by DandreChen** [andyli029/mysql-server-mysql-8.0.30#49]
engine_results.cpp:356:23: error: cannot convert ‘List<Item>’ to ‘const mem_root_deque<Item*>&’
  356 |   res->send_data(thd, fields);

engine_results.cpp:202:38: error: cannot convert ‘List<Item>’ to ‘const mem_root_deque<Item*>&’
  202 |   res->send_result_set_metadata(thd, fields, Protocol::SEND_NUM_ROWS | Protocol::SEND_EOF);

**Comment by andyli029** [comment]
`
Item ** find_item_in_list(Item *item, List<Item> &items, uint *counter,
                          find_item_error_report_type report_error,
                          enum_resolution_type *resolution);
->
Item **find_item_in_list(THD *thd, Item *item, mem_root_deque<Item *> *items,
                         uint *counter,
                         find_item_error_report_type report_error,
                         enum_resolution_type *resolution);
`
