### ISSUE TITLE
TODO: mysql_load is deleted by MySQL 8.0

### ISSUE THREAD

**Issue by andyli029** [andyli029/mysql-server-mysql-8.0.30#9]
```
engine.cpp line: 1134
if (mysql_load(thd, &ex, &tl, tmp_list, tmp_list, tmp_list, DUP_ERROR, false)) {
```

**Comment by lujiashun** [comment]
1、test steps
1.1、create table
CREATE TABLE `tmp_loaddata` (
`id` int(11) NOT NULL,
`name` varchar(10) DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=tianmu;
1.2  prepare data file
echo "1,new update"   >  /data/1.txt
echo "2,new update"   >> /data/1.txt
echo "3,new update"   >> /data/1.txt
1.3  load sql
LOAD DATA INFILE '/data/1.txt' Into TABLE tmp_loaddata FIELDS TERMINATED BY ',';

2.  coredump
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f1889636859 in __GI_abort () at abort.c:79
#2  0x00007f1889636729 in __assert_fail_base (
    fmt=0x7f18897cc588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x557700a42ffc "n < size()",
    file=0x557700a42fb8 "/data/codebase/mysql-server-mysql-8.0.30/include/prealloced_array.h", line=231,
    function=<optimized out>) at assert.c:92
#3  0x00007f1889647fd6 in __GI___assert_fail (assertion=0x557700a42ffc "n < size()",
    file=0x557700a42fb8 "/data/codebase/mysql-server-mysql-8.0.30/include/prealloced_array.h", line=231,
    function=0x557700a42f18 "Element_type& Prealloced_array<Element_type, Prealloc>::at(size_t) [with Elemen                                                                            t_type = Ha_data; long unsigned int Prealloc = 15; size_t = long unsigned int]") at assert.c:101
#4  0x00005576fd86b8cf in Prealloced_array<Ha_data, 15ul>::at (this=0x7f133c0029d8, n=18446744073709551615)
    at /data/codebase/mysql-server-mysql-8.0.30/include/prealloced_array.h:231
#5  0x00005576fd86b875 in Prealloced_array<Ha_data, 15ul>::operator[] (this=0x7f133c0029d8,
    n=18446744073709551615) at /data/codebase/mysql-server-mysql-8.0.30/include/prealloced_array.h:240
#6  0x00005576fd86b6aa in THD::get_ha_data (this=0x7f133c001060, slot=-1)
    at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_class.h:1599
#7  0x00005576ff9f940a in Tianmu::core::Engine::GetTx (this=0x5577076978c0, thd=0x7f133c001060)
    at /data/codebase/mysql-server-mysql-8.0.30/storage/tianmu/core/engine.cpp:914
#8  0x00005576ffab0a50 in Tianmu::dbhandler::TianmuHandler::external_lock (this=0x7f133c15a680,
    thd=0x7f133c001060, lock_type=1)
    at /data/codebase/mysql-server-mysql-8.0.30/storage/tianmu/handler/tianmu_handler.cpp:269
#9  0x00005576fdb5259b in handler::ha_external_lock (this=0x7f133c15a680, thd=0x7f133c001060, lock_type=1)
    at /data/codebase/mysql-server-mysql-8.0.30/sql/handler.cc:7790
#10 0x00005576fdda0684 in lock_external (thd=0x7f133c001060, tables=0x7f133c00e748, count=1)
    at /data/codebase/mysql-server-mysql-8.0.30/sql/lock.cc:393
#11 0x00005576fdda0309 in mysql_lock_tables (thd=0x7f133c001060, tables=0x7f133c15dea0, count=1, flags=0)
    at /data/codebase/mysql-server-mysql-8.0.30/sql/lock.cc:337
--Type <RET> for more, q to quit, c to continue without paging--
#12 0x00005576fd63346a in lock_tables (thd=0x7f133c001060, tables=0x7f133c15d830, count=1, flags=0) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_base.cc:6900
#13 0x00005576fd632a96 in open_and_lock_tables (thd=0x7f133c001060, tables=0x7f133c15d830, flags=0, prelocking_strategy=0x7f18387f4ed0)
    at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_base.cc:6594
#14 0x00005576fd58d112 in open_and_lock_tables (thd=0x7f133c001060, tables=0x7f133c15d830, flags=0) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_base.h:470
#15 0x00005576fdeca0ca in Sql_cmd_load_table::execute_inner (this=0x7f133c15d6f0, thd=0x7f133c001060, handle_duplicates=DUP_ERROR)
    at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_load.cc:248
#16 0x00005576fded189a in Sql_cmd_load_table::execute (this=0x7f133c15d6f0, thd=0x7f133c001060) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_load.cc:2144
#17 0x00005576fd73f616 in mysql_execute_command (thd=0x7f133c001060, first_level=true) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_parse.cc:3577
#18 0x00005576fd744ef2 in dispatch_sql_command (thd=0x7f133c001060, parser_state=0x7f18387f6b90) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_parse.cc:5239
#19 0x00005576fd73a971 in dispatch_command (thd=0x7f133c001060, com_data=0x7f18387f74e0, command=COM_QUERY) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_parse.cc:1959
#20 0x00005576fd7389e8 in do_command (thd=0x7f133c001060) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_parse.cc:1362
#21 0x00005576fd97528f in handle_connection (arg=0x557709cf52c0) at /data/codebase/mysql-server-mysql-8.0.30/sql/conn_handler/connection_handler_per_thread.cc:302
#22 0x00005576ff896f5c in pfs_spawn_thread (arg=0x557709cf3f10) at /data/codebase/mysql-server-mysql-8.0.30/storage/perfschema/pfs.cc:2942
#23 0x00007f188a828609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#24 0x00007f1889733133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by andyli029** [comment]
```
./storage/tianmu/core/engine.cpp:1126:    // the table will be opened in mysql_load
./storage/tianmu/core/engine.cpp:1138:    if (mysql_load(thd, &ex, &tl, tmp_list, tmp_list, tmp_list, DUP_ERROR, false)) {
./storage/tianmu/core/engine.cpp:1724:  bool local_load = false; // for_exporter ? false : (bool)(thd.lex)->local_file; // stonedb8 TODO: mysql_load
./storage/tianmu/core/engine.cpp:1725:  uint value_list_elements = 0; // (thd.lex)->load_value_list.elements; // stonedb8 TODO: mysql_load
```
